name: EasyDelivery CI - Validação do commit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pegar codigo do commit
        uses: actions/checkout@v6

      - name: iniciar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: instalar dependências
        run : npm install
        working-directory: ./api
      
      - name: Valida sintaxe da API
        run : npm run check
        working-directory: ./api
      
      - name: Realiza Linting da API 
        run : npm run lint
        working-directory: ./api

      - name: Executa os Testes unitários
        run : npm test
        working-directory: ./api

      - name: Faz o Build da Imagem Docker
        run : docker build -t EasyDelivery-API .
        working-directory: ./api